// <auto-generated />
using BookstoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookstoreApp.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookstoreApp.Models.Author", b =>
                {
                    b.Property<string>("AuthorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = "JKR",
                            FullName = "J.K. Rowling"
                        },
                        new
                        {
                            AuthorID = "JP",
                            FullName = "James Paterson"
                        },
                        new
                        {
                            AuthorID = "SK",
                            FullName = "Stephen King"
                        },
                        new
                        {
                            AuthorID = "CJ",
                            FullName = "Craig Johnson"
                        },
                        new
                        {
                            AuthorID = "KM",
                            FullName = "Kyle Mills"
                        });
                });

            modelBuilder.Entity("BookstoreApp.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GenreID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogoImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("PublisherID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("GenreID");

                    b.HasIndex("PublisherID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = "JKR",
                            GenreID = "F",
                            LogoImageSource = "fiction.jpg",
                            Price = 19.399999999999999,
                            PublisherID = "SN",
                            Quantity = 20,
                            Title = "Fiction 1",
                            Year = 2009
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = "CJ",
                            GenreID = "F",
                            LogoImageSource = "fiction.jpg",
                            Price = 25.120000000000001,
                            PublisherID = "C",
                            Quantity = 15,
                            Title = "Fiction 2",
                            Year = 2005
                        },
                        new
                        {
                            BookID = 3,
                            AuthorID = "SK",
                            GenreID = "H",
                            LogoImageSource = "horror.jpg",
                            Price = 12.76,
                            PublisherID = "MH",
                            Quantity = 2,
                            Title = "Horror 1",
                            Year = 2001
                        },
                        new
                        {
                            BookID = 4,
                            AuthorID = "JKR",
                            GenreID = "A",
                            LogoImageSource = "adventure.jpg",
                            Price = 27.870000000000001,
                            PublisherID = "C",
                            Quantity = 0,
                            Title = "Adventure 1",
                            Year = 2008
                        },
                        new
                        {
                            BookID = 5,
                            AuthorID = "JP",
                            GenreID = "A",
                            LogoImageSource = "adventure.jpg",
                            Price = 14.59,
                            PublisherID = "S",
                            Quantity = 25,
                            Title = "Adventure 2",
                            Year = 2004
                        },
                        new
                        {
                            BookID = 6,
                            AuthorID = "JP",
                            GenreID = "R",
                            LogoImageSource = "romance.jpg",
                            Price = 12.449999999999999,
                            PublisherID = "SN",
                            Quantity = 12,
                            Title = "Romance 1",
                            Year = 2019
                        },
                        new
                        {
                            BookID = 7,
                            AuthorID = "JKR",
                            GenreID = "R",
                            LogoImageSource = "romance.jpg",
                            Price = 9.7599999999999998,
                            PublisherID = "C",
                            Quantity = 3,
                            Title = "Romance 2",
                            Year = 2010
                        },
                        new
                        {
                            BookID = 8,
                            AuthorID = "SK",
                            GenreID = "H",
                            LogoImageSource = "horror.jpg",
                            Price = 10.43,
                            PublisherID = "MH",
                            Quantity = 35,
                            Title = "Horror 2",
                            Year = 1990
                        },
                        new
                        {
                            BookID = 9,
                            AuthorID = "KM",
                            GenreID = "M",
                            LogoImageSource = "mystery.jpg",
                            Price = 32.229999999999997,
                            PublisherID = "SN",
                            Quantity = 9,
                            Title = "Mystery 1",
                            Year = 1989
                        },
                        new
                        {
                            BookID = 10,
                            AuthorID = "CJ",
                            GenreID = "M",
                            LogoImageSource = "mystery.jpg",
                            Price = 12.67,
                            PublisherID = "H",
                            Quantity = 7,
                            Title = "Mystery 2",
                            Year = 2021
                        },
                        new
                        {
                            BookID = 11,
                            AuthorID = "JP",
                            GenreID = "A",
                            LogoImageSource = "adventure.jpg",
                            Price = 52.670000000000002,
                            PublisherID = "H",
                            Quantity = 17,
                            Title = "Adventure 3",
                            Year = 2013
                        });
                });

            modelBuilder.Entity("BookstoreApp.Models.Genre", b =>
                {
                    b.Property<string>("GenreID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = "F",
                            Name = "Fiction"
                        },
                        new
                        {
                            GenreID = "M",
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreID = "R",
                            Name = "Romance"
                        },
                        new
                        {
                            GenreID = "A",
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreID = "H",
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("BookstoreApp.Models.Publisher", b =>
                {
                    b.Property<string>("PublisherID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublisherID");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherID = "H",
                            Name = "Hachette"
                        },
                        new
                        {
                            PublisherID = "C",
                            Name = "Conestoga"
                        },
                        new
                        {
                            PublisherID = "MH",
                            Name = "McGraw-Hill"
                        },
                        new
                        {
                            PublisherID = "S",
                            Name = "Scholastics"
                        },
                        new
                        {
                            PublisherID = "SN",
                            Name = "Springer Nature"
                        });
                });

            modelBuilder.Entity("BookstoreApp.Models.Book", b =>
                {
                    b.HasOne("BookstoreApp.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID");

                    b.HasOne("BookstoreApp.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID");

                    b.HasOne("BookstoreApp.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherID");

                    b.Navigation("Author");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });
#pragma warning restore 612, 618
        }
    }
}
