// <auto-generated />
using System;
using A2_TransactionRecord.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace A2_TransactionRecord.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20211010070744_Company")]
    partial class Company
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("A2_TransactionRecord.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Address = "USA",
                            Name = "Microsoft",
                            TickerSymbol = "MSFT"
                        },
                        new
                        {
                            CompanyId = 2,
                            Address = "USA",
                            Name = "Google",
                            TickerSymbol = "GOOG"
                        });
                });

            modelBuilder.Entity("A2_TransactionRecord.Models.TransactionRecordKbaek7943", b =>
                {
                    b.Property<int>("TransactionRecordKbaek7943Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("SharePrice")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("TransactionTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TransactionRecordKbaek7943Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("TransactionRecordKbaek7943s");

                    b.HasData(
                        new
                        {
                            TransactionRecordKbaek7943Id = 1,
                            CompanyId = 1,
                            Quantity = 100,
                            SharePrice = 123.45,
                            TransactionTypeId = "Sell"
                        },
                        new
                        {
                            TransactionRecordKbaek7943Id = 2,
                            CompanyId = 2,
                            Quantity = 100,
                            SharePrice = 2701.7600000000002,
                            TransactionTypeId = "Buy"
                        });
                });

            modelBuilder.Entity("A2_TransactionRecord.Models.TransactionType", b =>
                {
                    b.Property<string>("TransactionTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Commission")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionTypeId");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            TransactionTypeId = "Buy",
                            Commission = 5.9900000000000002,
                            Name = "Buy"
                        },
                        new
                        {
                            TransactionTypeId = "Sell",
                            Commission = 5.4000000000000004,
                            Name = "Sell"
                        });
                });

            modelBuilder.Entity("A2_TransactionRecord.Models.TransactionRecordKbaek7943", b =>
                {
                    b.HasOne("A2_TransactionRecord.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A2_TransactionRecord.Models.TransactionType", "TrasactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("TrasactionType");
                });
#pragma warning restore 612, 618
        }
    }
}
