// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PressYourLuck.Models;

namespace PressYourLuck.Migrations
{
    [DbContext(typeof(PressLuckContext))]
    [Migration("20211109121247_Audit")]
    partial class Audit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PressYourLuck.Models.Audit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audits");

                    b.HasData(
                        new
                        {
                            AuditId = 1,
                            Amount = 400.0,
                            CreatedDate = new DateTime(2021, 11, 9, 21, 12, 47, 421, DateTimeKind.Local).AddTicks(4965),
                            PlayerName = "Jack"
                        },
                        new
                        {
                            AuditId = 2,
                            Amount = 400.0,
                            CreatedDate = new DateTime(2021, 11, 9, 21, 12, 47, 422, DateTimeKind.Local).AddTicks(4452),
                            PlayerName = "Rack"
                        },
                        new
                        {
                            AuditId = 3,
                            Amount = 430.0,
                            CreatedDate = new DateTime(2021, 11, 9, 21, 12, 47, 422, DateTimeKind.Local).AddTicks(4467),
                            PlayerName = "Hack"
                        },
                        new
                        {
                            AuditId = 4,
                            Amount = 450.0,
                            CreatedDate = new DateTime(2021, 11, 9, 21, 12, 47, 422, DateTimeKind.Local).AddTicks(4470),
                            PlayerName = "Zack"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
