// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PressYourLuck.Models;

namespace PressYourLuck.Migrations
{
    [DbContext(typeof(PressLuckContext))]
    [Migration("20211109121500_AuditType")]
    partial class AuditType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PressYourLuck.Models.Audit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("AuditTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditTypeId");

                    b.ToTable("Audits");

                    b.HasData(
                        new
                        {
                            AuditId = 1,
                            Amount = 400.0,
                            AuditTypeId = "Cash In",
                            CreatedDate = new DateTime(2021, 11, 9, 21, 14, 59, 876, DateTimeKind.Local).AddTicks(9796),
                            PlayerName = "Jack"
                        },
                        new
                        {
                            AuditId = 2,
                            Amount = 400.0,
                            AuditTypeId = "Cash Out",
                            CreatedDate = new DateTime(2021, 11, 9, 21, 14, 59, 877, DateTimeKind.Local).AddTicks(9271),
                            PlayerName = "Rack"
                        },
                        new
                        {
                            AuditId = 3,
                            Amount = 430.0,
                            AuditTypeId = "Win",
                            CreatedDate = new DateTime(2021, 11, 9, 21, 14, 59, 877, DateTimeKind.Local).AddTicks(9285),
                            PlayerName = "Hack"
                        },
                        new
                        {
                            AuditId = 4,
                            Amount = 450.0,
                            AuditTypeId = "Lose",
                            CreatedDate = new DateTime(2021, 11, 9, 21, 14, 59, 877, DateTimeKind.Local).AddTicks(9287),
                            PlayerName = "Zack"
                        });
                });

            modelBuilder.Entity("PressYourLuck.Models.AuditType", b =>
                {
                    b.Property<string>("AuditTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditTypeId");

                    b.ToTable("AuditTypes");

                    b.HasData(
                        new
                        {
                            AuditTypeId = "Cash In",
                            Name = "Cash In"
                        },
                        new
                        {
                            AuditTypeId = "Cash Out",
                            Name = "Cash Out"
                        },
                        new
                        {
                            AuditTypeId = "Win",
                            Name = "Win"
                        },
                        new
                        {
                            AuditTypeId = "Lose",
                            Name = "Lose"
                        });
                });

            modelBuilder.Entity("PressYourLuck.Models.Audit", b =>
                {
                    b.HasOne("PressYourLuck.Models.AuditType", "AuditTypes")
                        .WithMany()
                        .HasForeignKey("AuditTypeId");

                    b.Navigation("AuditTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
