using System;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Registration.Models
{
    public class Customer
    {
        // PK (autogenerated by database)
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "Please enter a username.")]
        [RegularExpression("(?i)^[a-z0-9]+$", ErrorMessage = "Usernames cannot contain spaces or special characters.")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Please enter an email address.")]
        [Remote("CheckEmail", "Validation")]
        public string EmailAddress { get; set; }

        [Required(ErrorMessage = "Please enter a date of birth.")]
        [MinimumAge(13, ErrorMessage = "You must be at least 13 years old to be a customer.")]
        public DateTime? DOB { get; set; }

        [Required(ErrorMessage = "A credit card # is required")]
        [CreditCard(ErrorMessage = "Please enter a valid credit card #")]
        public string CreditCardNumber { get; set; }

        [Required(ErrorMessage = "Please enter a password.")]
        [StringLength(25, ErrorMessage = "Your password cannot exceed 25 characters.")]
        [Compare("PasswordConfirmation")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please confirm your password.")]
        [Display(Name = "Confirm Password")]
        [NotMapped()]
        public string PasswordConfirmation { get; set; }
    }
}