using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesListApp.Models
{
    public class Genre
    {
        // This is our PK field BUT, since it isn't an int, by default
        // it will NOT be auto-generated by the DB - i.e. we will have
        // to specify it ourselves manually
        public string GenreId { get; set; }
        public string Name { get; set; }

        // Add a navigation property to get all
        // Movies of this Genre:
        public ICollection<Movie> Movies { get; set; }
    }
}
