// <auto-generated />
using System;
using HeartRateApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeartRateApp.Migrations
{
    [DbContext(typeof(HeartRateDbContext))]
    partial class HeartRateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeartRateApp.Models.HeartRateMeasurement", b =>
                {
                    b.Property<int>("HeartRateMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BPMValue")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HeartRateMeasurementId");

                    b.ToTable("HeartRateMeasurements");

                    b.HasData(
                        new
                        {
                            HeartRateMeasurementId = 1,
                            BPMValue = 143,
                            MeasurementDate = new DateTime(2021, 10, 12, 10, 20, 50, 994, DateTimeKind.Local).AddTicks(2303)
                        },
                        new
                        {
                            HeartRateMeasurementId = 2,
                            BPMValue = 156,
                            MeasurementDate = new DateTime(2021, 10, 12, 10, 20, 50, 994, DateTimeKind.Local).AddTicks(3099)
                        },
                        new
                        {
                            HeartRateMeasurementId = 3,
                            BPMValue = 167,
                            MeasurementDate = new DateTime(2021, 10, 12, 10, 20, 50, 994, DateTimeKind.Local).AddTicks(3114)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
